import Container from "@/components/custom/Container";
import Row from "@/components/custom/Row";
import Products from "@/components/modules/Products";
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbList,
  BreadcrumbSeparator,
} from "@/components/ui/breadcrumb";
import { Metadata } from "next";
import Link from "next/link";
import React from "react";

const page = () => {
  return (
    <>
      <section className="">
        <Container>
          <Row>
            <Breadcrumb>
              <BreadcrumbList>
                <BreadcrumbItem>
                  <Link
                    href="/"
                    className="text-xl text-gray-400 hover:text-primary-500 text-pretty"
                  >
                    Home
                  </Link>
                </BreadcrumbItem>
                <BreadcrumbSeparator />
                <Link
                  href="/products"
                  className="hover:text-primary-500 font-bold text-gray-400 text-xl text-pretty"
                >
                  Store
                </Link>
              </BreadcrumbList>
            </Breadcrumb>
          </Row>
        </Container>
      </section>
      <Products />
    </>
  );
};

export default page;

export const metadata: Metadata = {
  title: "Ecommer",
  description: "Generated by create next app",
  icons: {
    icon: "/public/assets/images/broWser-logo.png",
  },
};
