import type { Metadata } from "next";

import "./globals.css";
import Providers from "@/providers";
import { kanit } from "./font";
import * as React from "react";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Ecommer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={kanit.className}>
        <Providers>{children}</Providers>
        <Toaster closeButton richColors position="top-right" />
      </body>
    </html>
  );
}
